name: 'cdcup'
services:
  jobmanager:
    image: 'flink:1.20.3-scala_2.12'
    hostname: 'jobmanager'
    ports:
      - '8081'
    command: 'jobmanager'
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        execution.checkpointing.interval: 3000
  taskmanager:
    image: 'flink:1.20.3-scala_2.12'
    hostname: 'taskmanager'
    command: 'taskmanager'
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        execution.checkpointing.interval: 3000
  mysql:
    image: 'mysql:8.0'
    hostname: 'mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'cdcup'
    ports:
      - '3306'
    volumes:
      - 'cdc-data:/data'
  doris:
    image: 'apache/doris:doris-all-in-one-2.1.0'
    hostname: 'doris'
    ports:
      - '8030'
      - '8040'
      - '9030'
    volumes:
      - 'cdc-data:/data'
volumes:
  cdc-data:
