---
pipeline:
  parallelism: 1
source:
  type: mysql
  hostname: mysql
  port: 3306
  username: root
  password: ''
  tables: 'database0.\.*'
  server-id: 15401
  server-time-zone: UTC
sink:
  type: doris
  fenodes: doris:8030
  benodes: doris:8040
  jdbc-url: jdbc:mysql://doris:9030
  username: root
  password: ''
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1
  sink.enable-delete: true
